version: '3.9'

services:

  etl:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/opt/data

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=warehouse
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: